---
platforms:
  - name: localhost
    image: alpine:3.8
ansible:
  #inventory_file: ./inventory.yml
  #vault_password_file: .vault
driver:
  name: docker
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: default
